### ISSUE TITLE
how to build it

### ISSUE THREAD

**Issue by xiaoshuye147** [xnoro/device_lenovo_moba#1]
hey,bro.
can you help me,please

**Comment by xnoro** [comment]
ya, how to build what?

for using this in compilation, if im not wrong you will need the vendor and the kernel source or use prebuilt kernel

then u use these with the source of one rom like lineageOs or other, and you can compile

but idk if this dt is good, if you will try, test with lineage os source, unfortunately i dint have pc to compile, so i stopped in this step

if you want, we can talk telegram, there is best, my user is @taotaoS2, pm me
